###服务启动端口号
server:
  port: 8600
###服务名称(服务注册到eureka名称)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name:  app-w-goods
  jedis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wen-goods?useUnicode=true&characterEncoding=UTF-8
  data:
    elasticsearch:
      ####集群名称
      cluster-name: elasticsearch-cluster
      ####地址
      cluster-nodes: 192.168.32.128:9300
  kafka:
    # kafka服务器地址（可以多个）
    bootstrap-servers: 192.168.32.128:9092
