#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-w-portal-pay-web
    session:
      store-type: redis
    redis:
      host: 127.0.0.1
      port: 6379
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8080/eureka
server:
  port: 8600
#redis:
# hostname: 192.168.32.128
# port: 6379
# password: 123456

xxl-sso:
  excluded:
    paths:
xxl:
  sso:
    server: http://xxlssoserver.com:8500/xxl-sso-server
    logout:
      path: /logout
    redis:
      address: redis://127.0.0.1:6379

