server:
  port: 8088
logging:
  config: classpath:logback.xml
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: xxl-job-pay-job
      port: 9999
      logretentiondays: -1
      ip: 
    admin:
      addresses: http://127.0.0.1:8083/xxl-job-admin
    accessToken: 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka